def initial_score():
    return {
        "team": "", "team1": "", "team2": "",
        "team1Fkey": "", "team2Fkey": "",
        "team1Img": "", "team2Img": "",
        "battingTeam": "", "bowlingTeam": "",
        "battingTeamFkey": "", "bowlingTeamFkey": "",
        "battingTeamImg": "", "bowlingTeamImg": "",
        "venue": "", "matchTime": "", "toss": "",
        "score": "0/0", "over": "0.0", "rr": "0.00",
        "event": "", "ticker": "", "commentaryText": "", "winChance": "",
        "lastBallRuns": "", "lastBatter": "", "lastBowler": "", "lastBallSpeed": "",
        "reviewEvent": "", "reviewText": "", "reviewPlayer": "",
        "thisOver": [], "recentOvers": [],
        "squadPlayers": [],
        "team1Squad": [], "team2Squad": [],
        "batsmen": [], "batsmenStats": [], "striker": "", "nonStriker": "",
        "bowler": "", "bowlerStats": {},
        "lastWicket": "", "partnership": "",
        "matchResult": "",
        "winnerTeam": "",
        "inningsBreak": False,
        "inningsBreakText": "",
        "target": "",
        "inningsLimitBalls": "",
        "inning": "",
    }
